export const CARD_BG = [
  { id: 1, bgcolor: "linear-gradient(135deg, #e6af83 0%, #fff1ca 100%)" },
  { id: 2, bgcolor: "linear-gradient(135deg, #e7e9ef 0%, #ffd4 100%)" },
  { id: 3, bgcolor: "linear-gradient(135deg, #a7eff7 0%, #bffbf 100%)" },
  { id: 4, bgcolor: "linear-gradient(135deg, #ff7e2b 0%, #fffa 100%)" },
  { id: 5, bgcolor: "linear-gradient(135deg, #f076fe 0%, #fffad 100%)" },
  { id: 6, bgcolor: "linear-gradient(135deg, #5f5f5f 0%, #bfdbfb 100%)" },
  { id: 7, bgcolor: "linear-gradient(135deg, #ff4f4f 0%, #fffdba 100%)" },
  { id: 8, bgcolor: "linear-gradient(135deg, #e8ef3 0%, #f5ef8 100%)" },
  { id: 9, bgcolor: "linear-gradient(135deg, #d0ecff 0%, #f5ff 100%)" },
  { id: 10, bgcolor: "linear-gradient(135deg, #ff2f2b 0%, #fff8f8 100%)" },
];

export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas — no generic prep.",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top — making your learning more organized.",
  },
  {
    id: "04",
    title: 'Understand the "Why" Behind Answers',
    description:
      "Beyond just answers — unlock detailed concept explanations generated by AI, helping you truly master each topic.",
  },
  {
    id: "05",
    title: "Save, Organize, and Revisit",
    description:
      "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation right where you left off.",
  },
];
